# Generated by Django 5.0.6 on 2024-06-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[("so'm", "so'm"), ('$', '$'), ('R', 'R')], default="so'm", max_length=100),
        ),
    ]
